### ISSUE TITLE
Make use of Gson Annotation "@SerializedName"

### ISSUE THREAD

**Issue by Jezza** [NPException42/Dimensional-Pockets#44]
When you check for backwards compatibility, with the Pocket, spawnSet, is it because you don't have the field in the older ones?
If so, annotation by the name of @SerialisedName with the name, will use that name instead of the field name.

**Comment by NPException42** [comment]
TIL. I didn't know about that annotation, thanks!
But since I don't want the serialized name to stay "spawnSet", what I would really need would be some kind of way to deserialize both names, which does not seem possible without a huge overhead.

But I will add that annotation to all the non transient fields of Pocket. Just so we don't forget about it should we rename a field again in the future.

**Comment by Jezza** [comment]
I know that there are annotations for getting a field that didn't exist in a version. 
@Until and @From or something. 
All you need to do is specify the version number that you want to serialise and de-serialise.

**Comment by NPException42** [comment]
Just looked at those. They are called `@Until` and `@Since`.

`@Since` does not seem very helpful for our case, unless we want older versions of DP to be able to load data created by newer ones. Well, actually it could make sense if changes made in a version only affect the server side, and the clients would not need to update. Which actually does not sound too bad. But on the other hand, since Gson ignores values that are not part of the class it is deserializing anyway, we don't really need it. 

The `@Until` annotation is not usefull at all. It would prevent  the `spawnSet` field from deserializing. `@Until` would only be helpful if we throw away a field completely, not just rename it.

**Comment by Jezza** [comment]
Ah, ok then. Just thought I'd mention it.

**Comment by NPException42** [comment]
Done
