### ISSUE TITLE
Colorblind considerations

### ISSUE THREAD

**Issue by Greylocke** [NPException42/Dimensional-Pockets#55]
Please consider the surprisingly large percentage of players that have some level of color blindness when designing the configuration for the pocket block. Other mod devs make use of mouseovers that display the color in text form or make use of patterns + color to make the configuration immediately apparent.

Thanks!

**Comment by Jezza** [comment]
I'm currently away at the moment, but I'm sure NP would love to jump on top of this. 

@NPException42 just make it an integer config for the different types of colourblind.

**Comment by NPException42** [comment]
I'll just make a boolean config option `colorblind_mode = true/false`. Bothering with the different types of colorblindness seems to much of a hassle, since we don't really need to use color correction methods. I'll rather use different overlay textures for each case then.

For the different modes of the sides it is actually no problem at all. The code is already built in a way that supports having a different overlay texture for each state. One for energy transfer, one for whatever comes.

The only thing that does not support that (yet) is the color coding of the different block sides. But I also just made that yesterday anyway. :D

Shouldn't be a problem to use letters instead of colored spots on the block sides to indicate the direction.

I'll take a shot at it later today.

**Comment by NPException42** [comment]
done. we just need to keep it in mind for future features

**Comment by Greylocke** [comment]
Nice! Thanks, guys!
