### ISSUE TITLE
Make the recipes editable via config

### ISSUE THREAD

**Issue by NPException42** [NPException42/Dimensional-Pockets#63]

**Comment by Jezza** [comment]
No, imbalance issues.  

There's a reason we're hard coding them in the first place.  
We can make it a level of difficulty thing if you wish.

**Comment by NPException42** [comment]
The reasone we were hard coding them was simply the time restriction during ModJam, nothing else.

A level of difficulty thing would result in having multiple hardcoded recipes, which are chosen based on a single number. That's just unnecessarily bloating the code, imo.

I'd rather have them freely configurable. Reason being that, depending on other mods installed, the resources necessary might be too hard or too easy to obtain.

The recipe isn't something we really need to enforce on players. >90% of them won't touch the config file anyway. The other ones might want to integrate DP into the overall tone of their own "mod pack" and might want to exchange the stone bricks with warded stone f.e.

**Comment by Jezza** [comment]
I disagree that it was a time constraint.  
Hard coding crafting recipes was not because we lacked time. It's because that's what we wanted. We wanted it to be hard to obtain. 

If a mod pack dev wants to fit the mod in with their theme, well, I'm sorry, but if the mod doesn't fit their theme in the first place, why bother adding it? 

I disagree with customisable recipes.

**Comment by NPException42** [comment]
I have a hard time trying to understand why you are so strongly against making recipes customizeable. 

Of course making different difficulty levels would be a compromise solution, but that would rule out the ability to use other mod's stuff as ingredients entirely.

The only peole who would alter recipes at all know how to do so even without our mod giving them this freedom. So why making stuff unnecessarily hard for those people?

**Comment by NPException42** [comment]
In addition, not having customiseable recipes wont satisfy my desire to @Config all the things :D

**Comment by Jezza** [comment]
The reason I'm so against it, is because it's going to be ugly. 
Ids aren't a thing anymore. They're a per world thing now, so you'd have to get the user to find out the localised name of the items, and mod Ids, which granted might not be too hard, but it would be a lot of work and it's going to be an ugly mess of shit. 
I'm also against it because it's a decision we decided on, if they want a different experience, why are they using this? We chose those items for a couple of reasons. The need or want to remove the hardcoded recipes is unnecessary and far too much work for the two people that will use it. 
On top of that, if someone likes our mod after using it through a mod pack, and in that mod pack they changed the recipe, they're going to get to the default recipe, and just get confused and then they'll have to dig through and either set it up to the recipe they're used to, or just ignore it. 
On top of all that, I don't want a server make the recipe really hard or really easy when the objects are overpowered. In the event of it being a harder recipe, I don't like the idea of a server added more difficulty to it then needed. It almost feels like they're withholding the mod.

**Comment by Jezza** [comment]
You could probably test custom config annotations to register your own config annotation for custom recipes. Not condoning the custom recipes, just saying custom annotations are awesome...

**Comment by NPException42** [comment]
> On top of that, if someone likes our mod after using it through a mod pack, and in that mod pack they changed the recipe, they're going to get to the default recipe, and just get confused and then they'll have to dig through and either set it up to the recipe they're used to, or just ignore it. 

Now THAT's a reason I can follow. I agree. Case closed.

**PS:** Creating the recipes should not be too hard, as it would just be a 9 elements long json list of "modID:unlocalizedName". The same way pretty much every other mod with customiseable recipes does it (mods that i know of)

**Comment by NPException42** [comment]
Although we might consider having a Peacefull difficulty alternative recipe

**Comment by Jezza** [comment]
Yeah, but 9 fairly long strings isn't going to be pretty, the config would be the prettiest.  
I actually wouldn't even know how to get the item given the tag. And we'd have to make sure we load after them, I think. 

A peaceful recipe I can agree on. Make it end stone instead of pearls.
