### ISSUE TITLE
Server does not start if a pocket has it's source block in a dynamically loaded dimension

### ISSUE THREAD

**Issue by mrgrey1** [NPException42/Dimensional-Pockets#75]
I recently tried to use Dimensiaonal Pockets in a Galacticraft dimension (Mars) and ran into a bug. The dimensional pocket will function as intended until the server is restarted. The server will then refuse to restart throwing a Null Pointer Exception. Is repeatable. http://pastebin.com/r8iBxmF2

**Comment by NPException42** [comment]
Hi, thanks for the info! I encountered this bug myself just about 6 hours before your post. :D

The bug is not related to Galacticraft alone, but can happen with any mod that does not register/load it's dimensions on server start. (In my case it was Mystcraft)

What happens is that at server start DP tries to initiate chunkloading for all DP-Rooms which have their respective DP placed somewhere. Problem is that it cannot get the world where the DP is placed (or was last placed) because it is not yet loaded at this point.

I try to throw out a hotfix for that later today.

Unfortunately, so far I only know how to prevent the error by ignoring it. But that will result the affected DP rooms not beeing chunkloaded. If I find a better solution for that today, I will use that for the hotfix instead.

**Comment by NPException42** [comment]
This is problem is now worked around in the release (0.10.5): http://minecraft.curseforge.com/mc-mods/226990-dimensional-pockets

Only downside of the work around is, that affected DP rooms will not be chunkloaded after every server restart until they are broken and placed down again.

**Comment by mrgrey1** [comment]
How would having an independent chunkloader like chickenchunks in the DP room affect this?

**Comment by NPException42** [comment]
That will work perfectly fine. Infact, that is what I'm doing on my own
private server. Just plop down a Spotloader in the Pocket and you are good
to go. :)

**Comment by mrgrey1** [comment]
Excellent! was hoping that'd be an option. Love your work, keep it up and thanks. 
Cheers.
